-- Rol de aplicación: solo DML (mínimo privilegio). Sin SUPERUSER ni DDL.
CREATE ROLE pandora_app WITH LOGIN PASSWORD 'strong_app_password'
    NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION;

-- Base de datos de la aplicación
GRANT CONNECT ON DATABASE pandora TO pandora_app;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM pandora_app;
GRANT USAGE ON SCHEMA public TO pandora_app;

ALTER DEFAULT PRIVILEGES FOR ROLE pandora IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pandora_app;
ALTER DEFAULT PRIVILEGES FOR ROLE pandora IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO pandora_app;

-- Base de datos de PHPUnit (phpunit.xml → DB_DATABASE=testing)
CREATE DATABASE testing OWNER pandora;
GRANT CONNECT ON DATABASE testing TO pandora_app;

\c testing

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM pandora_app;
GRANT USAGE ON SCHEMA public TO pandora_app;

ALTER DEFAULT PRIVILEGES FOR ROLE pandora IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pandora_app;
ALTER DEFAULT PRIVILEGES FOR ROLE pandora IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO pandora_app;
