CREATE ROLE pandora_app WITH LOGIN PASSWORD 'strong_app_password' SUPERUSER;
GRANT CONNECT ON DATABASE pandora TO pandora_app;
GRANT USAGE ON SCHEMA public TO pandora_app;
GRANT ALL ON SCHEMA public TO pandora_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pandora_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pandora_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pandora_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO pandora_app;
